### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by PraneethRavichandran** [Xiaoming-Zhao/PointNav-VO#13]
694th chunk size: 256

[177700 / 1000000] ep: 4008, 0.56s / episode; remain: 10326.45s

[177750 / 1000000] ep: 4009, 0.56s / episode; remain: 10325.04s

[177800 / 1000000] ep: 4009, 0.56s / episode; remain: 10323.50s

[177850 / 1000000] ep: 4010, 0.56s / episode; remain: 10322.19s

Traceback (most recent call last):
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/pointnav_vo/vo/dataset/generate_datasets.py", line 687, in <module>
    main()
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/pointnav_vo/vo/dataset/generate_datasets.py", line 682, in main
    obs_transformer=obs_transformer,
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/pointnav_vo/vo/dataset/generate_datasets.py", line 549, in generate_datasets
    obs_transformer=obs_transformer,
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/pointnav_vo/vo/dataset/generate_datasets.py", line 401, in generate_one_dataset
    prev_obs = env.reset()
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/habitat-lab/habitat/core/env.py", line 259, in reset
    observations=observations,
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/habitat-lab/habitat/core/embodied_task.py", line 162, in reset_measures
    measure.reset_metric(*args, **kwargs)
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/habitat-lab/habitat/tasks/nav/nav.py", line 599, in reset_metric
    episode=episode, task=task, *args, **kwargs
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/habitat-lab/habitat/tasks/nav/nav.py", line 620, in update_metric
    self._start_end_episode_distance, self._agent_episode_distance
ZeroDivisionError: float division by zero

-------------------------------------------------------------------------------------------------------------------------------------
A little context about the issue, 
During installation we had to use the newest version of Habitat-lab and Habitat-sim . 
Added to that, only the nightly version of installation was succeed . - conda install habitat-sim -c conda-forge -c aihabitat-nightly.

The issue occured when we ran generate_datasets.py with the following config. 
--config_f /home/desktop-obs-68/projects/visual-odometry/PointNav-VO/configs/point_nav_habitat_challenge_2020.yaml 
--train_scene_dir ./dataset/habitat_datasets/pointnav/gibson/v2/train/content 
--val_scene_dir ./dataset/habitat_datasets/pointnav/gibson/v2/val/content 
--save_dir ./dataset/vo_dataset 
--data_version v2  
--vis_size_w 341  
--vis_size_h 192  
--obs_transform none  
--act_type -1  
--rnd_p 1.0  
--N_list 1000000 
--name_list train

**Comment by Xiaoming-Zhao** [comment]
Hi, please report this issue to the habitat team as the error comes from `env.reset()` (inferred from your traceback), which is the package's function call.
