### ISSUE TITLE
Simulator.cpp(65)::~Simulator : Deconstructing Simulator

### ISSUE THREAD

**Issue by PraneethRavichandran** [Xiaoming-Zhao/PointNav-VO#14]
Environment creation successful
[20:41:53:580240]:[Physics] PhysicsManager.h(503)::addArticulatedObjectFromURDF : Not implemented in base PhysicsManager.
[20:41:53:580266]:[Core] ManagedContainerBase.h(205)::getObjectHandleByID : Unknown ArticulatedObject managed object ID: -1 . Aborting
[20:41:53:580296]:[Core] ManagedContainerBase.h(329)::checkExistsWithMessage : <ArticulatedObject>::getObjectCopyByID : Unknown ArticulatedObject managed object handle :  . Aborting
[20:41:53:580356]:[Physics] PhysicsManager.cpp(50)::~PhysicsManager : Deconstructing PhysicsManager
[20:41:53:580456]:[Scene] SceneManager.h(25)::~SceneManager : Deconstructing SceneManager
[20:41:53:580463]:[Scene] SceneGraph.h(25)::~SceneGraph : Deconstructing SceneGraph
[20:41:53:580758]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
[20:41:53:580858]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
[20:41:53:580998]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
[20:41:53:581013]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
[20:41:53:581049]:[Scene] SemanticScene.h(47)::~SemanticScene : Deconstructing SemanticScene
[20:41:53:584969]:[Gfx] Renderer.cpp(72)::~Impl : Deconstructing Renderer
[20:41:53:584996]:[Gfx] WindowlessContext.h(17)::~WindowlessContext : Deconstructing WindowlessContext
Traceback (most recent call last):
  File "examples/example.py", line 28, in <module>
    example()
  File "examples/example.py", line 17, in example
    observations = env.reset()  # noqa: F841
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/habitat-lab/habitat/core/env.py", line 253, in reset
    self.reconfigure(self._config)
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/habitat-lab/habitat/core/env.py", line 339, in reconfigure
    self._sim.reconfigure(self._config.SIMULATOR)
  File "/home/desktop-obs-68/projects/visual-odometry/PointNav-VO/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 171, in reconfigure
    self.robot.reconfigure()
  File "/home/desktop-obs-68/miniconda3/envs/pointnav-vo/lib/python3.7/site-packages/habitat_sim/robots/fetch_robot.py", line 75, in reconfigure
    super().reconfigure()
  File "/home/desktop-obs-68/miniconda3/envs/pointnav-vo/lib/python3.7/site-packages/habitat_sim/robots/mobile_manipulator.py", line 161, in reconfigure
    self.sim_obj.auto_clamp_joint_limits = True
AttributeError: 'NoneType' object has no attribute 'auto_clamp_joint_limits'
[20:41:53:712115]:[Sim] Simulator.cpp(65)::~Simulator : Deconstructing Simulator

This issue occurred after while executing  python examples/example.py

Should be noted that we have used the latest version of Habitat-lab and Habit-sim as we had faced with the Config file missing issue with the recommended commits of the repos.

**Comment by Xiaoming-Zhao** [comment]
Hi, you should report this issue with `habitat-lab` or `habitat-sim` as this is their `example.py`.
